package org.example;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class AutorizationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "E:\\ChromeDriver\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void main() {
    driver.get("https://diary.ru/");
    AutorizationPage autorizationPage = new AutorizationPage(driver);
    driver.manage().window().setSize(new Dimension(1536, 864));
    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
    autorizationPage.clickEnter();
    autorizationPage.clickLoginformUsername();
    autorizationPage.setLoginformUsername("sasha911a");
    autorizationPage.clickLoginformPassword();
    autorizationPage.setLoginformPassword("Co#gMpVcui");
    driver.switchTo().frame(0);
    autorizationPage.clickRecaptcha();
    driver.switchTo().defaultContent();
    autorizationPage.clickLogin();
    System.out.println("Test ended sucessfully!");
  }
}
