package org.example;// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.logging.LogEntries;
import org.openqa.selenium.logging.LogEntry;
import org.openqa.selenium.logging.LogType;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class AutorizationWixTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        LogEntries browserLogs = driver.manage().logs().get(LogType.BROWSER);
        List<LogEntry> allLogRows = browserLogs.getAll();
        if (allLogRows.size() > 0 ) {
            for(LogEntry info : allLogRows){

                System.out.println(info);
            }
        }
        driver.quit();
    }
    @Test
    public void main() {
        driver.get("https://users.wix.com/signin?view=sign-up&sendEmail=true&postSignUp=https:%2F%2Fuk.wix.com%2Fnew%2Fintro&loginCompName=Signup_H&referralInfo=Signup_H&postLogin=https:%2F%2Fuk.wix.com%2Fmy-account%2Fsites&forceRender=true");
        driver.manage().window().setSize(new Dimension(1920, 1080));
        AutorizationPageWix autorizationPageWix = new AutorizationPageWix(driver);
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        autorizationPageWix.clickLoginformUsername();
        autorizationPageWix.setLoginformUsername("sasha.ivanenko10@mail.ru");
        autorizationPageWix.clickLoginformPassword();
        autorizationPageWix.setLoginformPassword("1234567890");
        autorizationPageWix.clickAndHoldEnter().performEnter();
        autorizationPageWix.performEnter();
        autorizationPageWix.releaseEnter().performEnter();
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        autorizationPageWix.clickEnter();
        driver.close();
        System.out.println("Test ended sucessfully!");
    }
}