package org.example;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class AutorizationTestWix {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "E:\\ChromeDriver\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void main() {
        driver.get("https://users.wix.com/signin?view=sign-up&sendEmail=true&postSignUp=https:%2F%2Fuk.wix.com%2Fnew%2Fintro&loginCompName=Signup_H&referralInfo=Signup_H&postLogin=https:%2F%2Fuk.wix.com%2Fmy-account%2Fsites&forceRender=true");
        driver.manage().window().setSize(new Dimension(1920, 1080));
        assertTrue(driver.findElement(By.id("input_0")).isEnabled());
        driver.findElement(By.id("input_0")).click();
        driver.findElement(By.id("input_0")).sendKeys("sasha.ivanenko10@mail.ru");
        assertTrue(driver.findElement(By.id("input_1")).isEnabled());
        driver.findElement(By.id("input_1")).click();
        driver.findElement(By.id("input_1")).sendKeys("1234567890");
        {
            WebElement element = driver.findElement(By.name("submit"));
            Actions builder = new Actions(driver);
            assertTrue(element.isEnabled());
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.name("submit"));
            Actions builder = new Actions(driver);
            assertTrue(element.isEnabled());
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.name("submit"));
            Actions builder = new Actions(driver);
            assertTrue(element.isEnabled());
            builder.moveToElement(element).release().perform();
        }
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        assertTrue(driver.findElement(By.name("submit")).isEnabled());
        driver.findElement(By.name("submit")).click();
        driver.close();
        System.out.println("Test ended sucessfully!");
    }
}