package org.example;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class CreatingCopyOfTheProjectWixTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "E:\\ChromeDriver\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void creatingcopyoftheeproject() {
    driver.get("https://manage.wix.com/dashboard/0a4edbce-85c3-4c65-ab6f-b3269d24c898/home");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    assertTrue(driver.findElement(By.id("input_0")).isEnabled());
    driver.findElement(By.id("input_0")).click();
    driver.findElement(By.id("input_0")).sendKeys("sasha.ivanenko10@mail.ru");
    assertTrue(driver.findElement(By.id("input_1")).isEnabled());
    driver.findElement(By.id("input_1")).click();
    driver.findElement(By.id("input_1")).sendKeys("1234567890");
    {
      WebElement element = driver.findElement(By.name("submit"));
      Actions builder = new Actions(driver);
      assertTrue(element.isEnabled());
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.name("submit"));
      Actions builder = new Actions(driver);
      assertTrue(element.isEnabled());
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.name("submit"));
      Actions builder = new Actions(driver);
      assertTrue(element.isEnabled());
      builder.moveToElement(element).release().perform();
    }
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    assertTrue(driver.findElement(By.name("submit")).isEnabled());
    driver.findElement(By.name("submit")).click();
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    assertTrue(driver.findElement(By.cssSelector(".buttonnext1836296042__suffix")).isEnabled());
    driver.findElement(By.cssSelector(".buttonnext1836296042__suffix")).click();
    assertTrue(driver.findElement(By.cssSelector("div:nth-child(4) > .ListItemAction226466562__root .Text95380606__root")).isEnabled());
    driver.findElement(By.cssSelector("div:nth-child(4) > .ListItemAction226466562__root .Text95380606__root")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'wsr-modal1\']/div/div[3]/div/div/button[2]/span"));
      Actions builder = new Actions(driver);
      assertTrue(element.isEnabled());
      builder.moveToElement(element).clickAndHold().perform();
    }
    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'wsr-modal1\']/div/div[3]/div/div/button[2]/span"));
      Actions builder = new Actions(driver);
      assertTrue(element.isEnabled());
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'wsr-modal1\']/div/div[3]/div/div/button[2]/span"));
      Actions builder = new Actions(driver);
      assertTrue(element.isEnabled());
      builder.moveToElement(element).release().perform();
    }
    assertTrue(driver.findElement(By.xpath("//div[@id=\'wsr-modal1\']/div/div[3]/div/div/button[2]/span")).isEnabled());
    driver.findElement(By.xpath("//div[@id=\'wsr-modal1\']/div/div[3]/div/div/button[2]/span")).click();
    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
    driver.close();
    System.out.println("Test eneded sucessfully");
  }
}
