package org.example;// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.logging.LogEntries;
import org.openqa.selenium.logging.LogEntry;
import org.openqa.selenium.logging.LogType;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class CreatingCopyOfTheProjectWixTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeEach
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @AfterEach
    public void tearDown() {
        LogEntries browserLogs = driver.manage().logs().get(LogType.BROWSER);
        List<LogEntry> allLogRows = browserLogs.getAll();
        if (allLogRows.size() > 0 ) {
            for(LogEntry info : allLogRows){

                System.out.println(info);
            }
        }
        driver.quit();
    }

    @Test
    public void creatingcopyoftheeproject() {
        driver.get("https://manage.wix.com/dashboard/0a4edbce-85c3-4c65-ab6f-b3269d24c898/home");
        driver.manage().window().setSize(new Dimension(1920, 1080));
        AutorizationPageWix autorizationPageWix = new AutorizationPageWix(driver);
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        autorizationPageWix.clickLoginformUsername();
        autorizationPageWix.setLoginformUsername("sasha.ivanenko10@mail.ru");
        autorizationPageWix.clickLoginformPassword();
        autorizationPageWix.setLoginformPassword("1234567890");
        autorizationPageWix.clickAndHoldEnter().performEnter();
        autorizationPageWix.performEnter();
        autorizationPageWix.releaseEnter().performEnter();
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        autorizationPageWix.clickEnter();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

        CreatingCopyOfTheProjectWixPage creatingCopyOfTheProjectWixPage = new CreatingCopyOfTheProjectWixPage(driver);
        creatingCopyOfTheProjectWixPage.clickManage();
        creatingCopyOfTheProjectWixPage.clickCreateCopy();
        creatingCopyOfTheProjectWixPage.clickCreateCopyNext();
        creatingCopyOfTheProjectWixPage.clickLook();
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        driver.close();
        System.out.println("Test eneded sucessfully");
    }
}
